{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2a1a5f35-5845-4f8d-9a01-b233988f24cd",
   "metadata": {},
   "outputs": [],
   "source": [
    "# -*- coding: utf-8 -*-\n",
    "import streamlit as st\n",
    "import joblib\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import shap\n",
    "import matplotlib.pyplot as plt\n",
    "from sklearn.svm import SVC\n",
    "\n",
    "# 解决matplotlib绘图潜在后端问题\n",
    "plt.switch_backend('Agg')\n",
    "\n",
    "\n",
    "# -------------------------- 1. 路径配置（替换为相对路径，兼容所有环境） --------------------------\n",
    "MODEL_PATH = \"svm_best_model.pkl\"  # 仅保留文件名，同级目录直接读取\n",
    "SCALER_PATH = \"scaler.pkl\"          # 仅保留文件名，同级目录直接读取\n",
    "FEATURE_NAMES = [\"hb\", \"tt\", \"siri\", \"afr\", \"cea_log\", \"lvi\", \"t_stage\", \"n_stage\"]\n",
    "\n",
    "# -------------------------- 2. 加载模型和标准化器 --------------------------\n",
    "try:\n",
    "    # 加载线性SVM模型并验证\n",
    "    model = joblib.load(MODEL_PATH)\n",
    "    if not (isinstance(model, SVC) and model.kernel == \"linear\"):\n",
    "        st.error(\"加载的模型不是线性SVM，请检查模型文件路径！\")\n",
    "        st.stop()\n",
    "\n",
    "    # 加载标准化器\n",
    "    scaler = joblib.load(SCALER_PATH)\n",
    "    st.success(\"模型和标准化器加载成功！\")\n",
    "    st.info(f\"特征顺序：{FEATURE_NAMES}\")\n",
    "except Exception as e:\n",
    "    st.error(f\"加载失败：{str(e)}，请检查文件路径是否正确！\")\n",
    "    st.stop()\n",
    "\n",
    "# -------------------------- 3. 网页输入界面 --------------------------\n",
    "st.title(\"Gastric Cancer Liver Metastasis Predictor\")\n",
    "st.subheader(\"Input Feature Values\")\n",
    "\n",
    "user_input_dict = {}\n",
    "\n",
    "# 连续型特征输入\n",
    "user_input_dict[\"hb\"] = st.number_input(\"Hemoglobin (Hb, g/L)\", min_value=30.0, max_value=200.0, value=120.0, step=0.1)\n",
    "user_input_dict[\"tt\"] = st.number_input(\"Thrombin Time (TT, sec)\", min_value=5.0, max_value=30.0, value=13.0, step=0.1)\n",
    "user_input_dict[\"siri\"] = st.number_input(\"Systemic Inflammatory Response Index (SIRI)\", min_value=0.0, max_value=10.0, value=1.0, step=0.01)\n",
    "user_input_dict[\"afr\"] = st.number_input(\"Neutrophil/Lymphocyte Ratio (AFR)\", min_value=0.1, max_value=20.0, value=2.5, step=0.01)\n",
    "\n",
    "# CEA原始值自动转换为cea_log\n",
    "cea_original = st.number_input(\"CEA Original Value (ng/mL)\", min_value=0.0, max_value=1000.0, value=1.47, step=0.1)\n",
    "cea_log = np.log10(cea_original + 1)\n",
    "user_input_dict[\"cea_log\"] = cea_log\n",
    "st.caption(f\"CEA原始值={cea_original} → cea_log≈{cea_log:.6f}\")\n",
    "\n",
    "# 分类型特征输入\n",
    "user_input_dict[\"lvi\"] = st.selectbox(\"Lymphovascular Invasion (LVI)\", options=[0, 1], format_func=lambda x: \"No (0)\" if x==0 else \"Yes (1)\")\n",
    "user_input_dict[\"t_stage\"] = st.selectbox(\"T-stage\", options=[1, 2, 3, 4], format_func=lambda x: f\"T{x}\")\n",
    "user_input_dict[\"n_stage\"] = st.selectbox(\"N-stage\", options=[0, 1, 2, 3], format_func=lambda x: f\"N{x}\")\n",
    "\n",
    "# -------------------------- 4. 构造模型输入 --------------------------\n",
    "try:\n",
    "    user_input_list = [user_input_dict[feat] for feat in FEATURE_NAMES]\n",
    "    input_data = np.array(user_input_list).reshape(1, -1)\n",
    "except KeyError as e:\n",
    "    st.error(f\"特征缺失：{str(e)}，请检查特征名称是否一致！\")\n",
    "    st.stop()\n",
    "\n",
    "# -------------------------- 5. 预测逻辑 --------------------------\n",
    "if st.button(\"Predict Liver Metastasis Risk\"):\n",
    "    # 标准化输入数据\n",
    "    input_data_scaled = scaler.transform(input_data)\n",
    "\n",
    "    # 模型预测\n",
    "    predicted_class = model.predict(input_data_scaled)[0]\n",
    "    predicted_proba = model.predict_proba(input_data_scaled)[0]\n",
    "\n",
    "    # 展示预测结果\n",
    "    st.write(\"### Prediction Result\")\n",
    "    if predicted_class == 1:\n",
    "        risk_prob = predicted_proba[1] * 100\n",
    "        st.error(f\"**Liver Metastasis Risk: High Risk**\")\n",
    "        st.write(f\"Probability of Liver Metastasis: {risk_prob:.1f}%\")\n",
    "    else:\n",
    "        risk_prob = predicted_proba[0] * 100\n",
    "        st.success(f\"**Liver Metastasis Risk: Low Risk**\")\n",
    "        st.write(f\"Probability of No Liver Metastasis: {risk_prob:.1f}%\")\n",
    "\n",
    "    # 临床建议\n",
    "    st.write(\"### Clinical Advice\")\n",
    "    advice_high = (\n",
    "        \"1. Complete enhanced abdominal CT/MRI within 1 month to confirm metastasis;\\n\"\n",
    "        \"2. Monitor serological indicators (Hb, CEA) every 2 weeks;\\n\"\n",
    "        \"3. Consult an oncologist for adjuvant therapy (targeted/chemotherapy);\\n\"\n",
    "        \"4. Maintain a high-protein diet to improve anemia.\"\n",
    "    )\n",
    "    advice_low = (\n",
    "        \"1. Follow up (abdominal ultrasound + serology) every 3 months;\\n\"  \n",
    "        \"2. Avoid alcohol/spicy foods to reduce gastric irritation;\\n\"\n",
    "        \"3. Keep regular schedule & moderate exercise;\\n\"\n",
    "        \"4. Seek medical help for abdominal pain/jaundice/weight loss.\"\n",
    "    )\n",
    "    st.write(advice_high if predicted_class == 1 else advice_low)\n",
    "\n",
    "    # SHAP Force Plot\n",
    "    st.write(\"### Model Interpretation (SHAP Force Plot)\")\n",
    "    masker = shap.maskers.Independent(data=input_data_scaled, max_samples=100)\n",
    "    explainer = shap.LinearExplainer(model=model, masker=masker, feature_names=FEATURE_NAMES)\n",
    "    shap_values = explainer.shap_values(input_data_scaled)\n",
    "\n",
    "    # 绘制并展示力图\n",
    "    plt.figure(figsize=(12, 5))\n",
    "    shap.force_plot(\n",
    "        base_value=explainer.expected_value,\n",
    "        shap_values=shap_values,\n",
    "        features=pd.DataFrame(input_data_scaled, columns=FEATURE_NAMES),\n",
    "        matplotlib=True,\n",
    "        show=False,\n",
    "        plot_cmap=\"RdBu_r\"\n",
    "    )\n",
    "    plt.title(\"SHAP Force Plot: Feature Impact on Prediction\", fontsize=12)\n",
    "    plt.tight_layout()\n",
    "    plt.savefig(\"svm_shap_force_plot.png\", bbox_inches=\"tight\", dpi=300)\n",
    "    st.image(\"svm_shap_force_plot.png\")\n",
    "    st.caption(\"Red: Increase metastasis risk; Blue: Reduce metastasis risk; Length: Contribution degree\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
